# st = "Sun rises in east"
# print(len(st))
# print(st.lower())
# print(st.casefold())
# print(st.upper())
# print(st.title())
# print(st.capitalize())
# print(st)
# print(st.strip())
# print(st.replace('s','T',2))
# print(st.find(" "))
# print(st.startswith("su"))
# print(st.endswith("st"))
# print(st.split("s",2))
# print("abc".join("xyz"))
# print("abc".isalpha())
# print("123sdd".isdigit())
# print("abc12".isalnum())
# print("abc".zfill(10))
# print("abc".center(16,'*'))

