# Generated by Django 6.0.4 on 2026-05-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp_01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('qty', models.IntegerField()),
                ('inStock', models.IntegerField()),
                ('sold', models.IntegerField()),
            ],
        ),
    ]
